[project]
name = "geoloc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
    "typer>=0.15.2",
    "typing>=3.10.0.0",
]
